dubbo:
  scan:
    base-packages: com.want.dubbo.provider.service
  protocols:
    dubbo:
      port: -1

feign:
  hystrix:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata