dubbo:
  cloud:
    # The subscribed services in consumer side
    subscribed-services: ${provider.application.name}
  protocols:
    dubbo:
      port: -1
  consumer:
    check: false
    timeout: 5000
  scan:
    base-packages: com.want.dubbo.consumer.service

server:
  port: 8081

provider:
  application:
    name: spring-cloud-alibaba-dubbo-provider